/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula12;

/**
 *
 * @author MIGUELDONATODEMIRAND
 */
public class YouAre extends javax.swing.JFrame {

    int num = 0;
    int numAtual=0;

    /**
     * Creates new form YouAre
     */
    public YouAre() {
        initComponents();
            B1.setVisible(true);
    B2.setVisible(false);
    B4.setVisible(false);
    B5.setVisible(false);
    B6.setVisible(false);
    B7.setVisible(false);
    B8.setVisible(false);
    B9.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        Text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B1.setText("Não");
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B1MouseEntered(evt);
            }
        });

        B2.setText("Não");
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B2MouseEntered(evt);
            }
        });

        B3.setText("sim");
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B3MouseEntered(evt);
            }
        });
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setText("Não");
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B4MouseEntered(evt);
            }
        });

        B5.setText("Não");
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B5MouseEntered(evt);
            }
        });

        B6.setText("Não");
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B6MouseEntered(evt);
            }
        });

        B7.setText("Não");
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B7MouseEntered(evt);
            }
        });

        B8.setText("Não");
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B8MouseEntered(evt);
            }
        });

        B9.setText("Não");
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B9MouseEntered(evt);
            }
        });
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        Text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Text.setText("vc é gay?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B4)
                    .addComponent(B1)
                    .addComponent(B7))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B5)
                            .addComponent(B8)
                            .addComponent(B2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B3)
                            .addComponent(B6)
                            .addComponent(B9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1)
                    .addComponent(B2)
                    .addComponent(B3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B4)
                    .addComponent(B5)
                    .addComponent(B6))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B7)
                    .addComponent(B8)
                    .addComponent(B9))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseEntered
        fuction();
    }//GEN-LAST:event_B1MouseEntered

    private void B2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseEntered
 fuction();
    }//GEN-LAST:event_B2MouseEntered

    private void B3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseEntered


    }//GEN-LAST:event_B3MouseEntered

    private void B4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseEntered
fuction();
    }//GEN-LAST:event_B4MouseEntered

    private void B5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseEntered
fuction();
    }//GEN-LAST:event_B5MouseEntered

    private void B6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseEntered
fuction();
    }//GEN-LAST:event_B6MouseEntered

    private void B7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseEntered
fuction();        // TODO add your handling code here:
    }//GEN-LAST:event_B7MouseEntered

    private void B8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseEntered
fuction();        // TODO add your handling code here:
    }//GEN-LAST:event_B8MouseEntered

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B9ActionPerformed

    private void B9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MouseEntered
fuction();        // TODO add your handling code here:
    }//GEN-LAST:event_B9MouseEntered

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
Text.setText("la ele");
    B1.setVisible(false);
    B2.setVisible(false);
    B3.setVisible(false);
    B4.setVisible(false);
    B5.setVisible(false);
    B6.setVisible(false);
    B7.setVisible(false);
    B8.setVisible(false);
    B9.setVisible(false);
    }//GEN-LAST:event_B3ActionPerformed
void fuction(){
     num = (int) (Math.random() * 7);
     if(num==numAtual){num = (int) (Math.random() * 7);
         }
     if(num==numAtual){num = (int) (Math.random() * 7);
         }
     if(num==numAtual){num = (int) (Math.random() * 7);
         }
      if (num == 0 && 0 != numAtual) {
    B1.setVisible(true);
    B2.setVisible(false);
    B4.setVisible(false);
    B5.setVisible(false);
    B6.setVisible(false);
    B7.setVisible(false);
    B8.setVisible(false);
    B9.setVisible(false);
} else if (num == 1 && 1 != numAtual) {
    B1.setVisible(false);
    B2.setVisible(true);
    B4.setVisible(false);
    B5.setVisible(false);
    B6.setVisible(false);
    B7.setVisible(false);
    B8.setVisible(false);
    B9.setVisible(false);
} else if (num == 2 && 2 != numAtual) {
    B1.setVisible(false);
    B2.setVisible(false);
    B4.setVisible(true);
    B5.setVisible(false);
    B6.setVisible(false);
    B7.setVisible(false);
    B8.setVisible(false);
    B9.setVisible(false);
} else if (num == 3 && 3 != numAtual) {
    B1.setVisible(false);
    B2.setVisible(false);
    B4.setVisible(false);
    B5.setVisible(true);
    B6.setVisible(false);
    B7.setVisible(false);
    B8.setVisible(false);
    B9.setVisible(false);
} else if (num == 4 && 4 != numAtual) {
    B1.setVisible(false);
    B2.setVisible(false);
    B4.setVisible(false);
    B5.setVisible(false);
    B6.setVisible(true);
    B7.setVisible(false);
    B8.setVisible(false);
    B9.setVisible(false);
} else if (num == 5 && 5 != numAtual) {
    B1.setVisible(false);
    B2.setVisible(false);
    B4.setVisible(false);
    B5.setVisible(false);
    B6.setVisible(false);
    B7.setVisible(true);
    B8.setVisible(false);
    B9.setVisible(false);
} else if (num == 6 && 6 != numAtual) {
    B1.setVisible(false);
    B2.setVisible(false);
    B4.setVisible(false);
    B5.setVisible(false);
    B6.setVisible(false);
    B7.setVisible(false);
    B8.setVisible(true);
    B9.setVisible(false);
} else if (num == 7 && 7 != numAtual) {
    B1.setVisible(false);
    B2.setVisible(false);
    B4.setVisible(false);
    B5.setVisible(false);
    B6.setVisible(false);
    B7.setVisible(false);
    B8.setVisible(false);
    B9.setVisible(true);
}
      numAtual=num;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouAre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouAre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouAre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouAre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YouAre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JLabel Text;
    // End of variables declaration//GEN-END:variables
}
