/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conexao;

import java.sql.Connection;

public class App {

    public static void main(String[] args) {
        ConexaoSQLlite conexaoSQLite = new ConexaoSQLlite(); 
        Connection conexao = conexaoSQLite.conectar();

        if (conexao != null) {
            // Criar tabela
            CriarTabela.criarTabelaUsuarios(conexao);

            // Inserir usuário
            InserirUsuario.inserirUsuario(conexao, "miguel", "miguel@email.com");
            InserirUsuario.inserirUsuario(conexao,"emily","emily@mail");

            // Listar usuários
            ListarUsuario.listarUsuario(conexao);

            // Fechar conexão
            conexaoSQLite.desconectar(conexao);
        }
    }
}
