/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula10;

import javax.swing.ImageIcon;

/**
 *
 * @author MIGUELDONATODEMIRAND
 */
public class Quiz extends javax.swing.JFrame {
    String resposta;

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ba1 = new javax.swing.JButton();
        bb1 = new javax.swing.JButton();
        bc1 = new javax.swing.JButton();
        ba2 = new javax.swing.JButton();
        bb2 = new javax.swing.JButton();
        ba3 = new javax.swing.JButton();
        bb3 = new javax.swing.JButton();
        bc3 = new javax.swing.JButton();
        ba4 = new javax.swing.JButton();
        bb4 = new javax.swing.JButton();
        bc4 = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bc2 = new javax.swing.JButton();
        ba5 = new javax.swing.JButton();
        bb5 = new javax.swing.JButton();
        bc5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ba1.setText("a) Tornar-se o Rei dos Piratas");
        ba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba1ActionPerformed(evt);
            }
        });

        bb1.setText("b) Encontrar o All Blue");
        bb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb1ActionPerformed(evt);
            }
        });

        bc1.setText("c) Derrubar o Governo Mundial");
        bc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bc1ActionPerformed(evt);
            }
        });

        ba2.setText("a) Uso de Haki (Observação, Armamento ou Conquista)");
        ba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba2ActionPerformed(evt);
            }
        });

        bb2.setText("b) Controle sobre uma Fruta do Diabo (Paramecia, Zoan, Logia)");
        bb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb2ActionPerformed(evt);
            }
        });

        ba3.setText("a) East Blue");
        ba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba3ActionPerformed(evt);
            }
        });

        bb3.setText("b) Grand Line");
        bb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb3ActionPerformed(evt);
            }
        });

        bc3.setText("c) Ilha do Céu (Skypiea)  ");
        bc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bc3ActionPerformed(evt);
            }
        });

        ba4.setText("a) É inimigo dos Marines");
        ba4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba4ActionPerformed(evt);
            }
        });

        bb4.setText("b) Trabalhou com os Marines no passado");
        bb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb4ActionPerformed(evt);
            }
        });

        bc4.setText("c) Tem uma relação neutra ou sem interação com os Marines");
        bc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bc4ActionPerformed(evt);
            }
        });

        p1.setText("1. Qual é o principal objetivo do seu personagem?");

        jLabel2.setText("2. Qual é a principal habilidade do seu personagem?");

        jLabel3.setText("3. De onde seu personagem é originário?");

        jLabel4.setText("4. Qual é a relação do seu personagem com os Marines?");

        bc2.setText("c) Habilidade com espadas ou outras armas  ");
        bc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bc2ActionPerformed(evt);
            }
        });

        ba5.setText("a) Straw Hat Pirates (Bando do Luffy)");
        ba5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba5ActionPerformed(evt);
            }
        });

        bb5.setText("b) Whitebeard Pirates (Bando do Barba Branca)");
        bb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb5ActionPerformed(evt);
            }
        });

        bc5.setText("c) Beast Pirates (Bando do Kaido)");
        bc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bc5ActionPerformed(evt);
            }
        });

        jLabel5.setText("5. Qual é o bando ao qual seu personagem pertence?");

        jButton1.setText("ver resposta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("iniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ba2)
                            .addGap(18, 18, 18)
                            .addComponent(bb2)
                            .addGap(18, 18, 18)
                            .addComponent(bc2))
                        .addComponent(jLabel4)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ba1)
                                    .addGap(18, 18, 18)
                                    .addComponent(bb1)
                                    .addGap(18, 18, 18)
                                    .addComponent(bc1))
                                .addComponent(p1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(img)
                                        .addGap(27, 27, 27))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ba3)
                        .addGap(18, 18, 18)
                        .addComponent(bb3)
                        .addGap(18, 18, 18)
                        .addComponent(bc3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ba4)
                        .addGap(18, 18, 18)
                        .addComponent(bb4)
                        .addGap(18, 18, 18)
                        .addComponent(bc4))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ba5)
                        .addGap(18, 18, 18)
                        .addComponent(bb5)
                        .addGap(18, 18, 18)
                        .addComponent(bc5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(p1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ba1)
                            .addComponent(bb1)
                            .addComponent(bc1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(img)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ba2)
                    .addComponent(bb2)
                    .addComponent(bc2))
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ba3)
                    .addComponent(bb3)
                    .addComponent(bc3))
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ba4)
                    .addComponent(bb4)
                    .addComponent(bc4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ba5)
                    .addComponent(bb5)
                    .addComponent(bc5))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba1ActionPerformed
        img.setText(img.getText() + "a");
    }//GEN-LAST:event_ba1ActionPerformed

    private void bb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb1ActionPerformed
        img.setText(img.getText() + "b");
    }//GEN-LAST:event_bb1ActionPerformed

    private void ba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba3ActionPerformed
        img.setText(img.getText() + "a");
    }//GEN-LAST:event_ba3ActionPerformed

    private void ba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba2ActionPerformed
        img.setText(img.getText() + "a");
    }//GEN-LAST:event_ba2ActionPerformed

    private void ba4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba4ActionPerformed
        img.setText(img.getText() + "a");
    }//GEN-LAST:event_ba4ActionPerformed

    private void ba5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba5ActionPerformed
        img.setText(img.getText() + "a");
    }//GEN-LAST:event_ba5ActionPerformed

    private void bb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb2ActionPerformed
        img.setText(img.getText() + "b");
    }//GEN-LAST:event_bb2ActionPerformed

    private void bb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb3ActionPerformed
        img.setText(img.getText() + "b");
    }//GEN-LAST:event_bb3ActionPerformed

    private void bb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb4ActionPerformed
        img.setText(img.getText() + "b");
    }//GEN-LAST:event_bb4ActionPerformed

    private void bb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb5ActionPerformed
        img.setText(img.getText() + "b");
    }//GEN-LAST:event_bb5ActionPerformed

    private void bc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bc1ActionPerformed
        img.setText(img.getText() + "c");
    }//GEN-LAST:event_bc1ActionPerformed

    private void bc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bc2ActionPerformed
        img.setText(img.getText() + "c");
    }//GEN-LAST:event_bc2ActionPerformed

    private void bc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bc3ActionPerformed
        img.setText(img.getText() + "c");
    }//GEN-LAST:event_bc3ActionPerformed

    private void bc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bc4ActionPerformed
        img.setText(img.getText() + "c");
    }//GEN-LAST:event_bc4ActionPerformed

    private void bc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bc5ActionPerformed
        img.setText(img.getText() + "c");
    }//GEN-LAST:event_bc5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (img.getText().equals("abaaa")) {
            ImageIcon Im1 = new ImageIcon(getClass().getResource("luffy.png"));
            img.setIcon(Im1);
        } else if (img.getText().equals("acbab")) {
            ImageIcon Im1 = new ImageIcon(getClass().getResource("ace.jpg"));
            img.setIcon(Im1);
        } else if (img.getText().equals("bcaca")) {
            ImageIcon Im1 = new ImageIcon(getClass().getResource("sanji.jpg"));
            img.setIcon(Im1);
        } else if (img.getText().equals("cbbbc")) {
            ImageIcon Im1 = new ImageIcon(getClass().getResource("law.jpg"));
            img.setIcon(Im1);
        } else if (img.getText().equals("bcaba")) {
            ImageIcon Im1 = new ImageIcon(getClass().getResource("zoro.jpg"));
            img.setIcon(Im1);
        } else if (img.getText().equals("bbaba")) {
            ImageIcon Im1 = new ImageIcon(getClass().getResource("nami.jpg"));
            img.setIcon(Im1);
        } else if (img.getText().equals("cbbab")) {
            ImageIcon Im1 = new ImageIcon(getClass().getResource("bn.jpg"));
            img.setIcon(Im1);
        } else if (img.getText().equals("acbaa")) {
            ImageIcon Im1 = new ImageIcon(getClass().getResource("broak.jpg"));
            img.setIcon(Im1);
        } else {
            ImageIcon Im1 = new ImageIcon(getClass().getResource("nao.png"));
            img.setIcon(Im1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        img.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ba1;
    private javax.swing.JButton ba2;
    private javax.swing.JButton ba3;
    private javax.swing.JButton ba4;
    private javax.swing.JButton ba5;
    private javax.swing.JButton bb1;
    private javax.swing.JButton bb2;
    private javax.swing.JButton bb3;
    private javax.swing.JButton bb4;
    private javax.swing.JButton bb5;
    private javax.swing.JButton bc1;
    private javax.swing.JButton bc2;
    private javax.swing.JButton bc3;
    private javax.swing.JButton bc4;
    private javax.swing.JButton bc5;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel p1;
    // End of variables declaration//GEN-END:variables
}
